export const CREATE_SESSION = 'CREATE_SESSION';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILED = 'CREATE_SESSION_FAILED';

export const CANCEL_SESSION = 'CANCEL_SESSION';

export const END_SESSION = 'END_SESSION';
export const END_SESSION_SUCCESS = 'END_SESSION_SUCCESS';
export const END_SESSION_FAILED = 'END_SESSION_FAILED';

export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS';
export const RESTORE_SESSION_FAILED = 'RESTORE_SESSION_FAILED';

export const ACTIVATE_TRADE_SUCCESS = 'ACTIVATE_TRADE_SUCCESS';
export const ACTIVATE_TRADE_FAILED = 'ACTIVATE_TRADE_FAILED';

export const FETCH_TRADES_SUCCESS = 'FETCH_TRADES_SUCCESS';
export const FETCH_TRADES_FAILED = 'FETCH_TRADES_FAILED';

export const CLOSE_POSITION_SUCCESS = 'CLOSE_POSITION_SUCCESS';
export const CLOSE_POSITION_FAILED = 'CLOSE_POSITION_FAILED';

export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_FAILED = 'FETCH_SESSIONS_FAILED';