export const CREATE_SESSION = 'CREATE_SESSION';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILED = 'CREATE_SESSION_FAILED';

export const CANCEL_SESSION = 'CANCEL_SESSION';

export const END_SESSION = 'END_SESSION';
export const END_SESSION_SUCCESS = 'END_SESSION_SUCCESS';
export const END_SESSION_FAILED = 'END_SESSION_FAILED';

export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS';